version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: eventClean
    environment:
      POSTGRES_DB: eventClean
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"