CREATE TABLE Eventos (
id BIGSERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
description TEXT,
identificador VARCHAR(255) NOT NULL UNIQUE,
capacidade INTEGER NOT NULL,
organizador VARCHAR(255) NOT NULL,
local_evento VARCHAR(255),
data_inicio TIMESTAMP NOT NULL,
data_fim TIMESTAMP NOT NULL,
tipo VARCHAR(50) NOT NULL

)

